### ISSUE TITLE
ERROR_TYPE vocab discussion

### ISSUE THREAD

**Issue by jhnwllr** [gbif/occurrence-annotation#14]
Some thought is needed about the `ERROR_TYPE` vocab. 

We have to keep in mind that we are aiming to label areas on earth. Therefore, all occurrences that subsequently fall into that polygon have to fit the label. 

Some labels like `ENRICHMENT_TYPE : NATIVE` are not a problem because we expect all future occurrences to also be "native". 

However, a label like `ERROR_TYPE : IDENTIFICATION` is less likely to fit subsequent occurrences. Since a subsequent occurrence is not likely to be misidentification.

**Comment by timrobertson100** [comment]
Closing as error_type is removed, as per #16
