### ISSUE TITLE
sure fire plugin error when running tests with mvn

### ISSUE THREAD

**Issue by jhnwllr** [gbif/occurrence-annotation#35]
The backend-service tests inside IDEA work fine. 

However when you try to run tests using `mvn package --file backend-service/pom.xml` or any mvn build cmd `clean install` ect ... 

You get the following error. 

``` 
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project annotation: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/occurrence-annotation/occurrence-annotation/backend-service/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error: [ERROR] There was an error in the forked process
Error:  org/junit/platform/engine/EngineExecutionListener.NOOP
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
Error:  org/junit/platform/engine/EngineExecutionListener.NOOP
```

Here is an example from a github actions run. 
https://github.com/gbif/occurrence-annotation/actions/runs/6970047769/job/18967176203#step:6:129

**Comment by timrobertson100** [comment]
Can you please check this works for you now @jhnwllr and close this if so?
Thanks

**Comment by jhnwllr** [comment]
Thanks @timrobertson100 

It works now! 
https://github.com/gbif/occurrence-annotation/actions/runs/6971226073/job/18970802024
