### ISSUE TITLE
Set up stable environments for test

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence-annotation#37]
@jhnwllr would like to establish some groups for testing, for which we need stable deployments.

I suggest we deploy 2 installations, both configured to use production data - one for a GBIF Helpdesk team, and one for external use. They could both live within the same installation, but we may want to bring features to each at a different pace, so I think we might want to isolate these.

I presume this means to make a software maven release, setup two database in the GBIF UAT PG, and make 2 deployments of the app and UI.

Does this sound correct to you @jhnwllr please?

**Comment by jhnwllr** [comment]
Separate external and internal deployments sounds good to me. @timrobertson100 

How should we manage of the separate deployments? Different git branches? UAT (internal) and PROD/main (external)?

**Comment by jhnwllr** [comment]
@marcos-lg has set up endpoints on **dev**, **uat**, and **prod**: 

https://api.gbif.org/v1/occurrence/experimental/annotation/project
https://api.gbif-uat.org/v1/occurrence/experimental/annotation/project
https://api.gbif-dev.org/v1/occurrence/experimental/annotation/project

The swagger docs are also now working: 
http://prodws-vh.gbif.org:8124/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

Now the UI just needs to be moved, which I believe is being worked on by @zaultooz 
https://github.com/gbif/infrastructure/issues/19
After that we can close this issue

**Comment by MortenHofft** [comment]
> Now the UI just needs to be moved, which I believe is being worked on by @zaultooz

The UI is broken since the API had breaking changes. So that will need some days of reworking.

**Comment by jhnwllr** [comment]
https://labs.gbif.org/annotations/iframe.html?args=&id=tools-annotations--standalone-example&projectId=1&rulesetId=1&taxonKey=2288218&view=RULES&viewMode=story
